Makefile: Disable enum-conversion warning & unused-command-line-argument
- clang warning:

../drivers/platform/msm/ipa/ipa_v2/rmnet_ipa.c:442:34: warning: implicit conversion from enumeration type 'enum ipa_ip_type_enum_v01' to different enumeration type 'enum ipa_ip_type' [-Wenum-conversion]
                        rule_req->filter_spec_list[i].ip_type;
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
../drivers/platform/msm/ipa/ipa_v2/rmnet_ipa.c:444:34: warning: implicit conversion from enumeration type 'enum ipa_filter_action_enum_v01' to different enumeration type 'enum ipa_flt_action' [-Wenum-conversion]
                        rule_req->filter_spec_list[i].filter_action;
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~

error: argument unused during compilation: '-Wenum-conversion' [-Werror,-Wunused-command-line-argument]

Don't use the commit "msm: ipa_v2: Fix filter enum mismatch and ip_type conversion" -It breaks the mobile network.

Change-Id: 98f65bba2be91114861e4e1fb991b5b39c73b63b
Signed-off-by: TogoFire <italomellopereira@gmail.com>